name: Build and Deploy
on: 
  push:
    branches: [master]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Logseq Publish # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: pengx17/logseq-publish@0.1.0
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
